sudo: required
addons:
  sauce_connect:
    username: marcelklehr
    access_key:
      secure: C4errmkFcsqThedIIBeczzhGs20m8j5oCsowukSL23w0RcOcqOCA5om+DU/AvMwstex3zZI7TN1BJbyC16V5c2iOER+mfEYFEKiNWdCxh2BQ4J45IN3cwQg+fl9nOVUJxhYUXpuSXq9M63ObM3MHhS4SV5k+bmlaomKJVWbaKjRuPKebANkHUQPy0sUKAnrcfRt3uFH7qSrFKx8JRaZ930z+//0KyQo44I8TbpnsuyvIHc19Ko+04iDtZFPmNl3RwSLmnlpJ6V5o0kYxMHu+lEoTYOObUzPnTp3Vh2NufNbkzZu/lYkAGam9lNCoTl7/bJFKeOCgU5FCzYTTxvDShADOoISQ79PVc7dlqAPtLsiRcO7LW2l3Xhi7RUuJJoJlh9NfSHaCeTtTZUzayE+sCB8kJ6sql8EHVgpnkr1AMhsI4s85ys/9Dg9xdF/DH5ck4hcmaEHcHvaqlvG0STXZE5aFybyogPQiL/58qkzo/4hDQMi/jMFw4wkhlKywGCOtbU8p9jTla85ownk+qUdZilr9QTTPWm1rcK81V20x44DiygNs/M3N8W4bNhCFV+u9VLy5ZFhDiQrYTeTNYi+EQUQAtrohH0T8HmSkXD5lGxkLQtybA+2y131ZjZ1bxT4+U0U+eW+O+FPAo+7LcS8ORDNNnPmssSyAC37mbFKfGB4=

env:
  global:
    - SERVER=nextcloud/travis_ci/master
    - DB=sqlite
    - NC_APP=bookmarks
    - OC_USER=admin
    - OC_PASS=admin
    - NC_APP_VERSION=master
  matrix:
    - SERVER_BRANCH=master NC_APP_VERSION=master FLOCCUS_ADAPTER="fake standard" SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=master NC_APP_VERSION=master FLOCCUS_ADAPTER="fake standard" SELENIUM_BROWSER="firefox"

    - SERVER_BRANCH=stable13 NC_APP_VERSION=v0.11.0 FLOCCUS_ADAPTER="nextcloud " SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=stable13 NC_APP_VERSION=v0.11.0 FLOCCUS_ADAPTER="nextcloud " SELENIUM_BROWSER="firefox"

    - SERVER_BRANCH=stable15 NC_APP_VERSION=v1.0.6 FLOCCUS_ADAPTER="nextcloud " SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=stable15 NC_APP_VERSION=v1.0.6 FLOCCUS_ADAPTER="nextcloud " SELENIUM_BROWSER="firefox"
    - SERVER_BRANCH=stable15 NC_APP_VERSION=v1.0.6 FLOCCUS_ADAPTER="nextcloud-folders" SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=stable15 NC_APP_VERSION=v1.0.6 FLOCCUS_ADAPTER="nextcloud-folders" SELENIUM_BROWSER="firefox"

    - SERVER_BRANCH=stable16 NC_APP_VERSION=v1.1.1 FLOCCUS_ADAPTER="nextcloud " SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=stable16 NC_APP_VERSION=v1.1.1 FLOCCUS_ADAPTER="nextcloud " SELENIUM_BROWSER="firefox"
    - SERVER_BRANCH=stable16 NC_APP_VERSION=v1.1.1 FLOCCUS_ADAPTER="nextcloud-folders" SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=stable16 NC_APP_VERSION=v1.1.1 FLOCCUS_ADAPTER="nextcloud-folders" SELENIUM_BROWSER="firefox"
    - SERVER_BRANCH=stable16 NC_APP_VERSION=v1.1.1 FLOCCUS_ADAPTER="webdav" SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=stable16 NC_APP_VERSION=v1.1.1 FLOCCUS_ADAPTER="webdav" SELENIUM_BROWSER="firefox"

    - SERVER_BRANCH=master NC_APP_VERSION=master FLOCCUS_ADAPTER="nextcloud " SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=master NC_APP_VERSION=master FLOCCUS_ADAPTER="nextcloud " SELENIUM_BROWSER="firefox"
    - SERVER_BRANCH=master NC_APP_VERSION=master FLOCCUS_ADAPTER="nextcloud-folders" SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=master NC_APP_VERSION=master FLOCCUS_ADAPTER="nextcloud-folders" SELENIUM_BROWSER="firefox"
    - SERVER_BRANCH=master NC_APP_VERSION=master FLOCCUS_ADAPTER="webdav" SELENIUM_BROWSER="chrome"
    - SERVER_BRANCH=master NC_APP_VERSION=master FLOCCUS_ADAPTER="webdav" SELENIUM_BROWSER="firefox"

language: node_js
node_js:
  - '7'
before_script:
  # build floccus
  - npm run keygen
  - npm run build-release

  # install apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # configure apache virtual hosts
  - sudo cp -f test/apache-vhost.conf /etc/apache2/sites-available/000-default.conf

  # use php 7
  - phpenv global 7.1

  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # install nextcloud with bookmarks app
  - pushd .
  - cd ..
  - git clone --depth=50 --branch="$NC_APP_VERSION" "https://github.com/nextcloud/$NC_APP.git" "$NC_APP"
  - cd bookmarks
  - test -f composer.json && composer install || echo "Not running composer due to missing composer.json"
  - wget https://raw.githubusercontent.com/$SERVER/before_install.sh
  - sudo chmod +x ./before_install.sh
  - . ./before_install.sh "$NC_APP" "$SERVER_BRANCH" "$DB"
  - cd ../core || cd ../server
  - php occ app:enable "$NC_APP"

  # set apache htroot
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

  - popd

script:
  - npm test
